
import { Subject, Badge } from './types';

export const SCIENCE_SUBJECTS: Subject[] = [
  { id: 'bn2', nameEn: 'Bangla 2nd Paper', nameBn: 'বাংলা ২য় পত্র', papers: [2] },
  { id: 'en', nameEn: 'English', nameBn: 'ইংরেজি', papers: [1, 2] },
  { id: 'ict', nameEn: 'ICT', nameBn: 'আইসিটি', papers: [1] },
  { id: 'phy', nameEn: 'Physics', nameBn: 'পদার্থবিজ্ঞান', papers: [1, 2] },
  { id: 'che', nameEn: 'Chemistry', nameBn: 'রসায়ন', papers: [1, 2] },
  { id: 'mth', nameEn: 'Higher Math', nameBn: 'উচ্চতর গণিত', papers: [1, 2] },
  { id: 'bio', nameEn: 'Biology', nameBn: 'জীববিজ্ঞান', papers: [1, 2] },
];

export const BADGES: Badge[] = [
  { id: 'unstoppable', labelEn: 'Unstoppable', labelBn: 'অদম্য', symbol: '🔥', color: 'bg-orange-100 text-orange-600' },
  { id: 'focus_beast', labelEn: 'Focus Beast', labelBn: 'মনোযোগের রাজা', symbol: '⚡', color: 'bg-yellow-100 text-yellow-600' },
  { id: 'discipline', labelEn: 'Discipline Mode', labelBn: 'শৃঙ্খলিত', symbol: '🛡️', color: 'bg-blue-100 text-blue-600' },
  { id: 'rank_hunter', labelEn: 'Rank Hunter', labelBn: 'র‍্যাঙ্ক শিকারি', symbol: '🏆', color: 'bg-purple-100 text-purple-600' },
  { id: 'comeback', labelEn: 'Comeback Strong', labelBn: 'দৃঢ় প্রত্যাবর্তন', symbol: '🚀', color: 'bg-green-100 text-green-600' },
];

export const LOCALIZATION = {
  en: {
    welcome: 'Welcome',
    greeting: (name: string) => `Good morning, ${name} 🔥`,
    dailyGoal: 'Today\'s Goal',
    startStudy: 'Start Study',
    timer: 'Timer',
    stats: 'Analytics',
    aiCoach: 'AI Coach',
    settings: 'Settings',
    streak: 'Streak',
    points: 'Points',
    resumeSession: 'Resume Session?',
    weakSubject: 'Weak Subject',
    todayPlan: 'Today\'s Plan',
    studyRingLabel: 'Daily Progress',
    finish: 'Finish',
    pause: 'Pause',
    cancel: 'Cancel',
    subject: 'Subject',
    paper: 'Paper',
    topic: 'Topic',
    save: 'Save Session',
    difficulty: 'Difficulty',
    difficultyEasy: 'Easy',
    difficultyMedium: 'Medium',
    difficultyHard: 'Hard',
    enterName: 'Enter your name',
    selectLanguage: 'Select Language',
    setGoal: 'Set daily goal (mins)',
    getStarted: 'Continue',
    noSessions: 'No study sessions yet. Start today!',
    aiSuggestion: (sub: string) => `You should study ${sub} today.`,
    revisionNeeded: 'Revision Needed',
  },
  bn: {
    welcome: 'স্বাগতম',
    greeting: (name: string) => `শুভ সকাল, ${name} 🔥`,
    dailyGoal: 'আজকের লক্ষ্য',
    startStudy: 'পড়াশোনা শুরু করুন',
    timer: 'টাইমার',
    stats: 'অ্যানালিটিক্স',
    aiCoach: 'এআই কোচ',
    settings: 'সেটিংস',
    streak: 'স্ট্রিক',
    points: 'পয়েন্ট',
    resumeSession: 'সেশন আবার শুরু করবেন?',
    weakSubject: 'দুর্বল বিষয়',
    todayPlan: 'আজকের পরিকল্পনা',
    studyRingLabel: 'আজকের অগ্রগতি',
    finish: 'শেষ করুন',
    pause: 'বিরতি',
    cancel: 'বাতিল',
    subject: 'বিষয়',
    paper: 'পত্র',
    topic: 'টপিক',
    save: 'সেশন সংরক্ষণ',
    difficulty: 'কঠিন্যতা',
    difficultyEasy: 'সহজ',
    difficultyMedium: 'মাঝারি',
    difficultyHard: 'কঠিন',
    enterName: 'আপনার নাম লিখুন',
    selectLanguage: 'ভাষা নির্বাচন করুন',
    setGoal: 'লক্ষ্য নির্ধারণ (মিনিট)',
    getStarted: 'চালিয়ে যান',
    noSessions: 'এখনও কোনো সেশন নেই। আজই শুরু করুন!',
    aiSuggestion: (sub: string) => `আজ আপনার ${sub} পড়া উচিত।`,
    revisionNeeded: 'রিভিশন প্রয়োজন',
  }
};
